name: 'OpenTimestamps Github Action'
description: 'Timestamp your git tags on the Bitcoin blockchain'
author: 'Jonathan Zernik'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
  repoName:
    description: 'Full name of the repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput inputs.repoName }}
